# Generated by Django 3.2.13 on 2022-06-08 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
